### PR TITLE
Code base rewrite

### PR DESCRIPTION
**Pull request by L1teD**
Sorry i can't take a video right now, so please clone my fork and open 2 browser tabs xd

SO, what i've done is completely rewrited HTML and CSS parts (also half of index.js)
Now everything, as it should be in modern days, uses flexbox and not fixed margins which are hard to edit

Also i shifted color pallete a bit according to Ed's brandbook

UPD:
I'll pin a screenshot at least (top is old one)
image

### CODE REVIEW

**Review by vifiiy — CHANGES_REQUESTED** [review]
- Since this is a static overlay with a set width and height, using flexbox for everything isnt needed as it doesnt need to scale and causes bugs with values that are extremely large (for example pp on aspire maps)
- I made some stylistic choices myself, like centering the slash between currentPP and PPifFC.
- Personally not a fan of having the BPM CS AR OD HP being larger, it fills the box up by alot and causes it to be quite overwhelming. Since they arent extremely important values, and are still visible when watching stream on mobile fullscreen, I think this change is not needed.
- The fade animation for map statistics is nice 👍 
- As for the colors, you can leave them in right now, but I have a feeling that with the contrast from the forefront and osu 100% bg dim its a bit too bright. I get that they are ed's branding guidelines, but since it's changable by the user anyway, I'd prefer working with the original colors chosen.
- Codebase rewrite is nice, but I'll have to update myself real quick with it. I use capitals mostly since I'm originally a C# developer 😭 

Could you change:
- slash to be centered like before
- mapstats to be smaller like before
- bg colors to be darker like before
- attach 1 screenshot of a map like [this one](https://osu.ppy.sh/beatmapsets/594751#osu/1257904) to show that the pp counter and bpm counter dont break with aspire maps

**Comment by L1teD** [comment]
So i made changes you asked (almost)
Also i added changes from commits 174eb5feddcaf49e15778148a117811f2d1c0e58 and 2066baeb841eb1f8116405b883173c3e37bd0d05

And there's screenshots (yes i know second screenshot is absolute dogshit, gotta fix it bit later)
image
image

**Comment by L1teD** [comment]
I fixed position of pp values, and also added bpm visualizer because i think that's look cool :>

image

https://github.com/user-attachments/assets/fd2c13b0-7171-4b8d-b475-bcab3fade950

**Review by vifiiy — APPROVED** [review]
Good rewrite of codebase, additions added are very nice. Fixed merge conflicts and ready to merge this. lmk if you have any additional changes which you want to include

**Comment by vifiiy** [comment]
got approval for merge

**Pull request merged**
